vim.keymap.set("n", "<C-n>", ":bnext<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<C-p>", ":bprevious<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<C-S-n>", ":tabnext<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<C-S-p>", ":tabprevious<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "j", 'v:count ? "j" : "gj"', { expr = true })
vim.keymap.set("n", "k", 'v:count ? "k" : "gk"', { expr = true })
vim.keymap.set("n", "<F4>", vim.lsp.buf.format)

vim.keymap.set("n", "[d", vim.diagnostic.goto_prev, { desc = "Go to previous diagnostic" })
vim.keymap.set("n", "]d", vim.diagnostic.goto_next, { desc = "Go to next diagnostic" })
vim.keymap.set("n", "<Space>ds", vim.diagnostic.open_float, { desc = "Show diagnostic" })
vim.keymap.set("n", "<Space>dl", vim.diagnostic.setloclist, { desc = "Open diagnostics list" })

vim.keymap.set("n", "gD", vim.lsp.buf.declaration, { desc = "Go to declaration" })
vim.keymap.set("n", "gd", vim.lsp.buf.definition, { desc = "Go to definition" })
vim.keymap.set("n", "K", vim.lsp.buf.hover, { desc = "Show documentation" })
vim.keymap.set("n", "gi", vim.lsp.buf.implementation, { desc = "Go to implementation" })
vim.keymap.set("n", "ca", vim.lsp.buf.code_action, { desc = "Code action" })
vim.keymap.set("n", "gr", vim.lsp.buf.references, { desc = "Show references" })
